<?php
 // module/Contracts/view/contracts/contracts/add.phtml:

 $title = 'Add new contract';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('contracts', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('idcontract'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('description'));
 echo $this->formRow($form->get('date'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();