<?php
 // module/Contracts/view/contracts/contracts/delete.phtml:

 $title = 'Delete contract';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($contract->name); ?>' about
     '<?php echo $this->escapeHtml($contract->description); ?>'?
 </p>
 <?php
 $url = $this->url('contracts', array(
     'action'       => 'delete',
     'id'   => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $contract->idcontract; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>