<?php
 // module/Project/view/project/project/delete.phtml:

 $title = 'Delete project';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Are you sure that you want to delete
     '<?php echo $this->escapeHtml($project->name); ?>'
     '<?php echo $this->escapeHtml($project->description); ?>'
     '<?php echo $this->escapeHtml($project->budget); ?>'?
 </p>
 <?php
 $url = $this->url('project', array(
     'action' => 'delete',
     'idproject'     => $this->idproject,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="idproject" value="<?php echo (int) $project->idproject; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>