 <?php
 // module/Project/view/project/project/edit.phtml:

 $title = 'Edit project';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'project',
     array(
         'action' => 'edit',
         'idproject'     => $this->idproject,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('idproject'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('description'));
 echo $this->formRow($form->get('budget'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();