<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Developer\Module'                        => __DIR__ . '/Module.php',
    'Developer\Controller\IndexController' => __DIR__ . '/src/Developer/Controller/IndexController.php',
    'DeveloperTest\Framework\TestCase'        => __DIR__ . '/tests/Developer/Framework/TestCase.php',
    'DeveloperTest\SampleTest'                => __DIR__ . '/tests/Developer/SampleTest.php',
);
